test: 🧪 16

diff --git a/.github/workflows/start.yaml b/.github/workflows/start.yaml
--- a/.github/workflows/start.yaml
+++ b/.github/workflows/start.yaml
@@ -34,6 +34,7 @@ jobs:
       - name: Check instance state
         id: check_instance_state
         run: |
+         [ -z "$INSTANCE_ID" ] && echo "ERROR::Can't find an instance for deployment branch: $GITHUB_REF_NAME" && exit 1
          export STATE=$(aws ec2 describe-instances --output text --filters Name=instance-id,Values=$INSTANCE_ID --query "Reservations[].Instances[].State[].Name[]")
          echo $STATE
          echo "instance_state=$STATE" >> $GITHUB_OUTPUT
